name: Test

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Prepare files to archive
        run: |
          mkdir -p root/hoge/fuga/
          touch root/hoge/fuga/file
          touch root/file
        shell: bash

      - name: Create zip
        uses: ./
        with:
          root_dir: root
          file_path: root.zip
          verbose: true

      - name: Create tar
        uses: ./
        with:
          root_dir: root
          file_path: root.tar
          verbose: true

      - name: Create tar.gz
        uses: ./
        with:
          root_dir: root
          file_path: root.tar.gz
          verbose: true

      - name: Create tgz
        uses: ./
        with:
          root_dir: root
          file_path: root.tgz
          verbose: true

      - name: Create tar.bz2
        uses: ./
        with:
          root_dir: root
          file_path: root.tar.bz2
          verbose: true

      - name: Create tbz2
        uses: ./
        with:
          root_dir: root
          file_path: root.tbz2
          verbose: true

      - name: Create tar.xz
        uses: ./
        with:
          root_dir: root
          file_path: root.tar.xz
          verbose: true

      - name: Create txz
        uses: ./
        with:
          root_dir: root
          file_path: root.txz
          verbose: true

      - name: Check if all archives are created
        run: |
          check() {
            local file=$1
            test -f $file && echo "[$file] OK" || echo "[$file] NG"
          }
          ls root.*
          check root.zip
          check root.tar
          check root.tar.gz
          check root.tgz
          check root.tar.bz2
          check root.tbz2
          check root.tar.xz
          check root.txz
        shell: bash
