name: Test

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Prepare files to archive
        run: |
          mkdir -p root/hoge/fuga/
          touch root/hoge/fuga/file
          touch root/file
        shell: bash

      - name: Create zip
        uses: ./
        with:
          root_dir: root
          output: root.zip

      - name: Create tar
        uses: ./
        with:
          root_dir: root
          output: root.tar

      - name: Create tar.gz
        uses: ./
        with:
          root_dir: root
          output: root.tar.gz

      - name: Create tgz
        uses: ./
        with:
          root_dir: root
          output: root.tgz

      - name: Create tar.bz2
        uses: ./
        with:
          root_dir: root
          output: root.tar.bz2

      - name: Create tbz2
        uses: ./
        with:
          root_dir: root
          output: root.tbz2

      - name: Create tar.xz
        uses: ./
        with:
          root_dir: root
          output: root.tar.xz

      - name: Create txz
        uses: ./
        with:
          root_dir: root
          output: root.txz

      - name: Check if all archives are created
        run: |
          check() {
            local file=$1
            test -f $file && echo "[${file##.}] OK" || echo "[${file##.}] NG"
          }
          check root.zip
          check root.tar
          check root.tar.gz
          check root.tgz
          check root.tar.bz2
          check root.tbz2
          check root.tar.xz
          check root.txz
        shell: bash
