name: Test

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Prepare files to archive
        run: |
          mkdir -p root/hoge/fuga/
          touch root/hoge/fuga/file
          touch root/file
        shell: bash

      - name: Create zip
        uses: ./
        with:
          root_dir: root
          file_path: root.zip
          verbose: true
      - run: test -f root.zip
        shell: bash

      - name: Create tar
        uses: ./
        with:
          root_dir: root
          file_path: root.tar
          verbose: true
      - run: test -f root.tar
        shell: bash

      - name: Create tar.gz
        uses: ./
        with:
          root_dir: root
          file_path: root.tar.gz
          verbose: true
      - run: test -f root.tar.gz
        shell: bash

      - name: Create tgz
        uses: ./
        with:
          root_dir: root
          file_path: root.tgz
          verbose: true
      - run: test -f root.tgz
        shell: bash

      - name: Create tar.bz2
        uses: ./
        with:
          root_dir: root
          file_path: root.tar.bz2
          verbose: true
      - run: test -f root.tar.bz2
        shell: bash

      - name: Create tbz2
        uses: ./
        with:
          root_dir: root
          file_path: root.tbz2
          verbose: true
      - run: test -f root.tbz2
        shell: bash

      - name: Create tar.xz
        uses: ./
        with:
          root_dir: root
          file_path: root.tar.xz
          verbose: true
      - run: test -f root.tar.xz
        shell: bash

      - name: Create txz
        uses: ./
        with:
          root_dir: root
          file_path: root.txz
          verbose: true
      - run: test -f root.txz
        shell: bash