name: Test

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Prepare files to archive
        run: |
          mkdir -p root/hoge/fuga/
          touch root/hoge/fuga/file
          touch root/file
        shell: bash

      - name: Create zip
        uses: ./
        with:
          root_dir: root
          file_path: root.zip
          verbose: true
      - name: Extract zip
        uses: ihiroky/extract-action@main
        with:
          file_path: root.zip
          extract_dir: extract/zip
      - run: test -f extract/zip/hoge/fuga/file -a -f extract/zip/file

      - name: Create tar
        uses: ./
        with:
          root_dir: root
          file_path: root.tar
          verbose: true
      - name: Extract tar
        uses: ihiroky/extract-action@main
        with:
          file_path: root.tar
          extract_dir: extract/tar
      - run: test -f extract/tar/hoge/fuga/file -a -f extract/tar/file

      - name: Create tar.gz
        uses: ./
        with:
          root_dir: root
          file_path: root.tar.gz
          verbose: true
      - name: Extract tar.gz
        uses: ihiroky/extract-action@main
        with:
          file_path: root.tar.gz
          extract_dir: 'extract/tar.gz'
      - run: test -f extract/tar.gz/hoge/fuga/file -a -f extract/tar.gz/file

      - name: Create tgz
        uses: ./
        with:
          root_dir: root
          file_path: root.tgz
          verbose: true
      - name: Extract tgz
        uses: ihiroky/extract-action@main
        with:
          file_path: root.tgz
          extract_dir: 'extract/tgz'
      - run: test -f extract/tgz/hoge/fuga/file -a -f extract/tgz/file

      - name: Create tar.bz2
        uses: ./
        with:
          root_dir: root
          file_path: root.tar.bz2
          verbose: true
      - name: Extract tar.bz2
        uses: ihiroky/extract-action@main
        with:
          file_path: root.tar.bz2
          extract_dir: 'extract/tar.bz2'
      - run: test -f extract/tar.bz2/hoge/fuga/file -a -f extract/tar.bz2/file

      - name: Create tbz2
        uses: ./
        with:
          root_dir: root
          file_path: root.tbz2
          verbose: true
      - name: Extract tbz2
        uses: ihiroky/extract-action@main
        with:
          file_path: root.tbz2
          extract_dir: 'extract/tbz2'
      - run: test -f extract/tbz2/hoge/fuga/file -a -f extract/tbz2/file

      - name: Create tar.xz
        uses: ./
        with:
          root_dir: root
          file_path: root.tar.xz
          verbose: true
      - name: Extract tar.xz
        uses: ihiroky/extract-action@main
        with:
          file_path: root.tar.xz
          extract_dir: 'extract/tar.xz'
      - run: test -f extract/tar.xz/hoge/fuga/file -a -f extract/tar.xz/file

      - name: Create txz
        uses: ./
        with:
          root_dir: root
          file_path: root.txz
          verbose: true
      - name: Extract txz
        uses: ihiroky/extract-action@main
        with:
          file_path: root.txz
          extract_dir: 'extract/txz'
      - run: test -f extract/txz/hoge/fuga/file -a -f extract/txz/file